#.github/workflows/ci.yml
name: Python CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  quality-and-tests:
    name: Quality Checks & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Format Check with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github."

      - name: Run automated tests with pytest
        run: pytest --junit-xml=test-results.xml

      - name: Publish test results summary
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: "fEX"
        if: always()

  security:
    name: Security Audits
    runs-on: ubuntu-latest
    permissions:
      # Required for Semgrep to upload findings to the Security tab
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SAST scan with Semgrep
        # Semgrep is a modern, fast, and powerful SAST tool.
        # The config "p/bandit" runs a ruleset equivalent to Bandit's checks.
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/bandit"

      - name: Run dependency vulnerability scan with pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
