# .github/workflows/ci.yml
name: Python CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  quality-and-tests:
    name: Quality Checks & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Format Check with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github"

      - name: Run automated tests with pytest
        run: pytest --junit-xml=test-results.xml

      - name: Publish test results summary
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: "fEX"
        if: always()

  security:
    name: Security Audits
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run SAST scan with Bandit
        uses: PyCQA/bandit-action@v1
        with:
          run: bandit -r . -c pyproject.toml --format sarif --output bandit-results.sarif
        continue-on-error: true

      - name: Upload Bandit SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
          category: bandit
        if: always()

      - name: Run dependency vulnerability scan with pip-audit
        uses: pypa/gh-action-pip-audit@v1.3.2
        with:
          inputs: requirements.txt
