name: Prompt Log Updater

on:
  pull_request:
    types: [opened]

jobs:
  update-prompt-log:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: read
      issues: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      
      - name: Update prompt log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          python .github/scripts/update_prompt_log.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git diff --quiet project_knowledge/PROMPT_LOG.md; then
            echo "No changes to commit"
          else
            git add project_knowledge/PROMPT_LOG.md
            git commit -m "Update prompt log for PR #${{ github.event.pull_request.number }}"
            git push
          fi